apiVersion: apps/v1
kind: Deployment
metadata: #Dictionary
  name: myapp1-deployment
  namespace: test
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata: # Dictionary
      name: myapp1-pod
      labels: # Dictionary
        app: myapp1  # Key value pairs
    spec:
      containers: # List
        - name: myapp1-container
          image: ghcr.io/stacksimplify/kubenginxhelm:0.1.0
          ports:
            - containerPort: 80
          resources: # Dictionary
            limits: # Dictionary
              cpu: "500m"
              memory: "512Mi"
            requests: # Dictionary
              cpu: "200m"
              memory: "256Mi"
